### ISSUE TITLE
Updating for Elm 0.17

### ISSUE THREAD

**Issue by mrmurphy** [rogeriochaves/elm-test-example#1]
Thanks for writing your blog post on this! Looks like the post has been updated for 0.17, but the example hasn't. Just FYI.

**Comment by rogeriochaves** [comment]
@splodingsocks thanks, I've just [upgraded the blogpost to 0.18](https://medium.com/@_rchaves_/testing-in-elm-93ad05ee1832#.98smt73md) and since there is a boilerplate generator now, this repo is no longer needed
